# Generated by Django 3.1.1 on 2020-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('renda', models.IntegerField(help_text='Digite apenas números inteiros', verbose_name='renda')),
                ('pontuacao', models.CharField(default='563', editable=False, max_length=3, verbose_name='pontuacao')),
                ('aprovado', models.BooleanField(default=False, editable=False, verbose_name='aprovado')),
                ('pedido_em', models.DateTimeField(auto_now_add=True, verbose_name='pedido_em')),
            ],
        ),
    ]
