# Generated by Django 3.1.1 on 2020-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='pontuacao',
        ),
        migrations.AlterField(
            model_name='cartao',
            name='renda',
            field=models.IntegerField(),
        ),
    ]
