# Generated by Django 3.1.1 on 2020-09-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0002_auto_20200920_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='renda',
            field=models.IntegerField(max_length=7, verbose_name='Renda'),
        ),
    ]
