# Generated by Django 3.1.1 on 2020-09-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0002_auto_20200921_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='aprovacao',
            field=models.BooleanField(default=False, editable=False, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='credito',
            field=models.FloatField(default=0, editable=False, verbose_name='Crédito'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='pontuacao',
            field=models.CharField(default=0, editable=False, max_length=3, verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='pedido_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Pedido em'),
        ),
    ]
