# Generated by Django 3.1.1 on 2020-11-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0003_auto_20200922_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='aprovacao',
            field=models.CharField(default='Reprovado', editable=False, max_length=15, verbose_name='Cartão'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='pedido_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Pedido em'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='pontuacao',
            field=models.IntegerField(default=0, editable=False, verbose_name='Pontuação'),
        ),
    ]
