# Generated by Django 3.1.1 on 2020-11-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0004_auto_20201119_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=15, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
